export enum InsightCategory {
  PERSONALITY = 'PERSONALITY',
  CAREER = 'CAREER',
  RELATIONSHIPS = 'RELATIONSHIPS',
  HEALTH = 'HEALTH',
  SPIRITUALITY = 'SPIRITUALITY',
  LIFE_PURPOSE = 'LIFE_PURPOSE',
  CHALLENGES = 'CHALLENGES',
  OPPORTUNITIES = 'OPPORTUNITIES',
  FINANCES = 'FINANCES',
  PERSONAL_GROWTH = 'PERSONAL_GROWTH'
} 